nelmio_api_doc:
    documentation:
        info:
            title: CarPilot API
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)
            - ^/mock/ # Accepts routes under /api except /api/doc
