controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mock_api_routes:
    resource: routes/mock_plate.yaml

# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login:
    path: /api/login_check
